name: Build and Deploy Pages

on:
  push:
    branches: ["future/webpage"]
    # TOOD adopt once mereged

  workflow_dispatch:


permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PLANTUML_BIN: /usr/bin/plantuml
    steps:
      - name: Install missing packages
        run: sudo apt install -y graphviz plantuml
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install mkdocs and co
        run: pip install -r requirements.txt
      # - name: Install mkdocs and co
      #   run: mkdir -p diagrams/out
      # - name: Build Site
      #   run: mkdocs build
      - name: Build container
        run: docker build -t tk611-ag09-doc -f Dockerfile .
      - name: Build site
        run: docker run --rm -v $(pwd):/home/ag09 -w /home/ag09 tk611-ag09-doc mkdocs build
      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '_site'

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
